version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres          # User to create
      POSTGRES_PASSWORD: my-secret-pw   # User password
      POSTGRES_DB: silly_demo_db       # Database to create
    ports:
      - "5432:5432"                    # Host port : Container port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in Docker volume

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_ENDPOINT: db                 # Name of the db service
      DB_PORT: 5432
      DB_USER: postgres                # Database user
      DB_PASS: my-secret-pw            # Database password
      DB_NAME: silly_demo_db   
    ports:
      - "8080:8080"       
    depends_on:
      - db
    volumes:
      - .:/app                         # Bind mount for local development

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8081:80"                        # Expose port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your nginx.conf
    depends_on:
      - app                            # Ensure app is up before starting nginx

volumes:
  postgres_data:
