services:
  db:
    image: postgres:15
    container_name: silly-demo-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sillydemo
    ports:
      - "5432:5432"
    volumes:
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql

  silly-demo:
    build: .
    container_name: silly-demo-app
    volumes:
      - .:/app # Bind mount the current directory for development
      - /app/tmp # Avoid volume caching issues
    ports:
      - "8080:8080" 
    environment:
      - GO_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=sillydemo
    depends_on:
      - db
    command: [ "fresh" ]

  nginx:
    image: nginx:latest
    container_name: silly-demo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - silly-demo

volumes:
  pgdata: