apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.containerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silly-demo-nginx
  template:
    metadata:
      labels:
        app: silly-demo-nginx
    spec:
      containers:
        - name: {{ .Values.nginx.containerName }}
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.nginx.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
