apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.port }}
  selector:
    app: silly-demo-db
