apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: silly-demo-app
